In [ ]:
import pandas as pd

In [ ]:
data=pd.read_csv('addresses.csv')

In [ ]:
data

,id,location_id,address_1,address_2,city,state_province,postal_code,country
0,1,1,2600 Middlefield Road,NaN,Redwood City,CA,94063,US
1,2,2,24 Second Avenue,NaN,San Mateo,CA,94401,US
2,3,3,24 Second Avenue,NaN,San Mateo,CA,94403,US
3,4,4,24 Second Avenue,NaN,San Mateo,CA,94401,US
4,5,5,24 Second Avenue,NaN,San Mateo,CA,94401,US
5,6,6,800 Middle Avenue,NaN,Menlo Park,CA,94025-9881,US
6,7,7,500 Arbor Road,NaN,Menlo Park,CA,94025,US
7,8,8,800 Middle Avenue,NaN,Menlo Park,CA,94025-9881,US
8,9,9,2510 Middlefield Road,NaN,Redwood City,CA,94063,US
9,10,10,1044 Middlefield Road,NaN,Redwood City,CA,94063,US
10,11,11,2140 Euclid Avenue.,NaN,Redwood City,CA,94061,US
11,12,12,1044 Middlefield Road,2nd Floor,Redwood City,CA,94063,US
12,13,13,399 Marine Parkway.,NaN,Redwood City,CA,94065,US
13,14,14,660 Veterans Blvd.,NaN,Redwood City,CA,94063,US
14,15,15,1500 Valencia Street,NaN,San Francisco,CA,94110,US
15,16,16,1161 South Bernardo,NaN,Sunnyvale,CA,94087,US
16,17,17,409 South Spruce Avenue,NaN,South San Francisco,CA,94080,US
17,18,18,114 Fifth Avenue,NaN,Redwood City,CA,94063,US
18,19,19,19 West 39th Avenue,NaN,San Mateo,CA,94403,US
19,20,21,123 El Camino Real,NaN,Belmont,CA,94002,US
20,21,22,2013 Avenue of the fellows,Suite 100,San Francisco,CA,94103,US

In [ ]:
type(data)

pandas.core.frame.DataFrame

In [ ]:
data.head()#----- gives first 5 records

,id,location_id,address_1,address_2,city,state_province,postal_code,country
0,1,1,2600 Middlefield Road,NaN,Redwood City,CA,94063,US
1,2,2,24 Second Avenue,NaN,San Mateo,CA,94401,US
2,3,3,24 Second Avenue,NaN,San Mateo,CA,94403,US
3,4,4,24 Second Avenue,NaN,San Mateo,CA,94401,US
4,5,5,24 Second Avenue,NaN,San Mateo,CA,94401,US

In [ ]:
data.head(8)

,id,location_id,address_1,address_2,city,state_province,postal_code,country
0,1,1,2600 Middlefield Road,NaN,Redwood City,CA,94063,US
1,2,2,24 Second Avenue,NaN,San Mateo,CA,94401,US
2,3,3,24 Second Avenue,NaN,San Mateo,CA,94403,US
3,4,4,24 Second Avenue,NaN,San Mateo,CA,94401,US
4,5,5,24 Second Avenue,NaN,San Mateo,CA,94401,US
5,6,6,800 Middle Avenue,NaN,Menlo Park,CA,94025-9881,US
6,7,7,500 Arbor Road,NaN,Menlo Park,CA,94025,US
7,8,8,800 Middle Avenue,NaN,Menlo Park,CA,94025-9881,US

In [ ]:
data.tail()#---- gives last 5 records

,id,location_id,address_1,address_2,city,state_province,postal_code,country
16,17,17,409 South Spruce Avenue,NaN,South San Francisco,CA,94080,US
17,18,18,114 Fifth Avenue,NaN,Redwood City,CA,94063,US
18,19,19,19 West 39th Avenue,NaN,San Mateo,CA,94403,US
19,20,21,123 El Camino Real,NaN,Belmont,CA,94002,US
20,21,22,2013 Avenue of the fellows,Suite 100,San Francisco,CA,94103,US

In [ ]:
data.tail(7)

,id,location_id,address_1,address_2,city,state_province,postal_code,country
14,15,15,1500 Valencia Street,NaN,San Francisco,CA,94110,US
15,16,16,1161 South Bernardo,NaN,Sunnyvale,CA,94087,US
16,17,17,409 South Spruce Avenue,NaN,South San Francisco,CA,94080,US
17,18,18,114 Fifth Avenue,NaN,Redwood City,CA,94063,US
18,19,19,19 West 39th Avenue,NaN,San Mateo,CA,94403,US
19,20,21,123 El Camino Real,NaN,Belmont,CA,94002,US
20,21,22,2013 Avenue of the fellows,Suite 100,San Francisco,CA,94103,US

In [ ]:
data.columns

Index(['id', 'location_id', 'address_1', 'address_2', 'city', 'state_province',
       'postal_code', 'country'],
      dtype='object')

In [ ]:
list(data.columns)

['id',
 'location_id',
 'address_1',
 'address_2',
 'city',
 'state_province',
 'postal_code',
 'country']

In [ ]:
data.head(8)

,id,location_id,address_1,address_2,city,state_province,postal_code,country
0,1,1,2600 Middlefield Road,NaN,Redwood City,CA,94063,US
1,2,2,24 Second Avenue,NaN,San Mateo,CA,94401,US
2,3,3,24 Second Avenue,NaN,San Mateo,CA,94403,US
3,4,4,24 Second Avenue,NaN,San Mateo,CA,94401,US
4,5,5,24 Second Avenue,NaN,San Mateo,CA,94401,US
5,6,6,800 Middle Avenue,NaN,Menlo Park,CA,94025-9881,US
6,7,7,500 Arbor Road,NaN,Menlo Park,CA,94025,US
7,8,8,800 Middle Avenue,NaN,Menlo Park,CA,94025-9881,US

In [ ]:
data[['id', 'address_1']] #---- to only fatch selected columns as a output

    id                   address_1
0    1       2600 Middlefield Road
1    2            24 Second Avenue
2    3            24 Second Avenue
3    4            24 Second Avenue
4    5            24 Second Avenue
5    6           800 Middle Avenue
6    7              500 Arbor Road
7    8           800 Middle Avenue
8    9       2510 Middlefield Road
9   10       1044 Middlefield Road
10  11         2140 Euclid Avenue.
11  12       1044 Middlefield Road
12  13         399 Marine Parkway.
13  14          660 Veterans Blvd.
14  15        1500 Valencia Street
15  16         1161 South Bernardo
16  17     409 South Spruce Avenue
17  18            114 Fifth Avenue
18  19         19 West 39th Avenue
19  20          123 El Camino Real
20  21  2013 Avenue of the fellows

In [ ]:
data=pd.read_excel('airline1.xls')

In [ ]:
data

    YEAR       Y      W       R      L      K
0   1948   1.214  0.243  0.1454  1.415  0.612
1   1949   1.354  0.260  0.2181  1.384  0.559
2   1950   1.569  0.278  0.3157  1.388  0.573
3   1951   1.948  0.297  0.3940  1.550  0.564
4   1952   2.265  0.310  0.3559  1.802  0.574
5   1953   2.731  0.322  0.3593  1.926  0.711
6   1954   3.025  0.335  0.4025  1.964  0.776
7   1955   3.562  0.350  0.3961  2.116  0.827
8   1956   3.979  0.361  0.3822  2.435  0.800
9   1957   4.420  0.379  0.3045  2.707  0.921
10  1958   4.563  0.391  0.3284  2.706  1.067
11  1959   5.385  0.426  0.3856  2.846  1.083
12  1960   5.554  0.441  0.3193  3.089  1.481
13  1961   5.465  0.460  0.3079  3.122  1.736
14  1962   5.825  0.485  0.3783  3.184  1.926
15  1963   6.876  0.506  0.4180  3.263  2.041
16  1964   7.823  0.538  0.5163  3.412  1.997
17  1965   9.120  0.564  0.5879  3.623  2.257
18  1966  10.512  0.586  0.5369  4.074  2.742
19  1967  13.020  0.622  0.4443  4.710  3.564
20  1968  15.261  0.666  0.3052  5.217  4.767
21  1969  16.313  0.731  0.2332  5.569  6.511
22  1970  16.002  0.831  0.1883  5.495  7.627
23  1971  15.876  0.906  0.2023  5.334  8.673
24  1972  16.662  1.000  0.2506  5.345  8.331
25  1973  17.014  1.056  0.2668  5.662  8.557
26  1974  19.305  1.131  0.2664  5.729  9.508
27  1975  18.721  1.247  0.2301  5.722  9.062
28  1976  19.250  1.375  0.3452  5.762  8.262
29  1977  20.647  1.544  0.4508  5.877  7.474
30  1978  22.726  1.703  0.5877  6.108  7.104
31  1979  23.619  1.779  0.5346  6.852  6.874

In [ ]:
pd.read_excel("airline1.xls" , sheet_name="Sheet2")

   YEAR      Y      W       R      L      K
0  1948  1.214  0.243  0.1454  1.415  0.612
1  1949  1.354  0.260  0.2181  1.384  0.559
2  1950  1.569  0.278  0.3157  1.388  0.573
3  1951  1.948  0.297  0.3940  1.550  0.564
4  1952  2.265  0.310  0.3559  1.802  0.574
5  1953  2.731  0.322  0.3593  1.926  0.711
6  1954  3.025  0.335  0.4025  1.964  0.776
7  1955  3.562  0.350  0.3961  2.116  0.827
8  1956  3.979  0.361  0.3822  2.435  0.800

In [ ]:
pd.read_excel("airline1.xls" , sheet_name="Sheet3" , header=None)

       0       1      2       3      4      5
0   1960   5.554  0.441  0.3193  3.089  1.481
1   1961   5.465  0.460  0.3079  3.122  1.736
2   1962   5.825  0.485  0.3783  3.184  1.926
3   1963   6.876  0.506  0.4180  3.263  2.041
4   1964   7.823  0.538  0.5163  3.412  1.997
5   1965   9.120  0.564  0.5879  3.623  2.257
6   1966  10.512  0.586  0.5369  4.074  2.742
7   1967  13.020  0.622  0.4443  4.710  3.564
8   1968  15.261  0.666  0.3052  5.217  4.767
9   1969  16.313  0.731  0.2332  5.569  6.511
10  1970  16.002  0.831  0.1883  5.495  7.627
11  1971  15.876  0.906  0.2023  5.334  8.673
12  1972  16.662  1.000  0.2506  5.345  8.331
13  1973  17.014  1.056  0.2668  5.662  8.557
14  1974  19.305  1.131  0.2664  5.729  9.508
15  1975  18.721  1.247  0.2301  5.722  9.062

In [ ]:
data1=pd.read_excel("airline1.xls" , sheet_name="Sheet3" , header=None , names=['a','b','c','d','e','f'])

In [ ]:
data1.to_csv('test1.csv' , index= False)

In [ ]:
data1.head(5)

      a      b      c       d      e      f
0  1960  5.554  0.441  0.3193  3.089  1.481
1  1961  5.465  0.460  0.3079  3.122  1.736
2  1962  5.825  0.485  0.3783  3.184  1.926
3  1963  6.876  0.506  0.4180  3.263  2.041
4  1964  7.823  0.538  0.5163  3.412  1.997

In [ ]:
pd.read_csv('https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv')#---load data from github

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
pip install lxml

Requirement already satisfied: lxml in /usr/local/lib/python3.10/dist-packages (4.9.4)

In [ ]:
import pandas as pd

In [ ]:
data2=pd.read_html('https://www.basketball-reference.com/leagues/NBA_2015_totals.html')

In [ ]:
type(data2)

list

In [ ]:
data2[0]

,Rk,Player,Age,Team,Pos,G,GS,MP,FG,FGA,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Awards
0,1.0,James Harden,25.0,HOU,SG,81.0,81.0,2981.0,647.0,1470.0,...,75.0,384.0,459.0,565.0,154.0,60.0,321.0,208.0,2217.0,"MVP-2,AS,NBA1"
1,2.0,Stephen Curry,26.0,GSW,PG,80.0,80.0,2613.0,653.0,1341.0,...,56.0,285.0,341.0,619.0,163.0,16.0,249.0,158.0,1900.0,"MVP-1,AS,NBA1"
2,3.0,Russell Westbrook,26.0,OKC,PG,67.0,67.0,2302.0,627.0,1471.0,...,124.0,364.0,488.0,574.0,140.0,14.0,293.0,184.0,1886.0,"MVP-4,AS,NBA2"
3,4.0,LeBron James,30.0,CLE,SF,69.0,69.0,2493.0,624.0,1279.0,...,51.0,365.0,416.0,511.0,109.0,49.0,272.0,135.0,1743.0,"MVP-3,DPOY-13,AS,NBA1"
4,5.0,Damian Lillard,24.0,POR,PG,82.0,82.0,2925.0,590.0,1360.0,...,49.0,329.0,378.0,507.0,97.0,21.0,222.0,164.0,1720.0,AS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
647,489.0,Malcolm Lee,24.0,PHI,SG,1.0,0.0,2.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN
648,490.0,Kalin Lucas,25.0,MEM,PG,1.0,0.0,6.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,NaN
649,491.0,Ronny Turiaf,32.0,MIN,C,2.0,0.0,19.0,0.0,0.0,...,0.0,1.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,NaN
650,492.0,David Wear,24.0,SAC,PF,2.0,0.0,7.0,0.0,2.0,...,2.0,0.0,2.0,1.0,0.0,0.0,0.0,1.0,0.0,NaN
651,NaN,League Average,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
data2[0].to_csv("players.csv")

In [ ]:
pd.read_csv('/content/addresses.csv')

,id,location_id,address_1,address_2,city,state_province,postal_code,country
0,1,1,2600 Middlefield Road,NaN,Redwood City,CA,94063,US
1,2,2,24 Second Avenue,NaN,San Mateo,CA,94401,US
2,3,3,24 Second Avenue,NaN,San Mateo,CA,94403,US
3,4,4,24 Second Avenue,NaN,San Mateo,CA,94401,US
4,5,5,24 Second Avenue,NaN,San Mateo,CA,94401,US
5,6,6,800 Middle Avenue,NaN,Menlo Park,CA,94025-9881,US
6,7,7,500 Arbor Road,NaN,Menlo Park,CA,94025,US
7,8,8,800 Middle Avenue,NaN,Menlo Park,CA,94025-9881,US
8,9,9,2510 Middlefield Road,NaN,Redwood City,CA,94063,US
9,10,10,1044 Middlefield Road,NaN,Redwood City,CA,94063,US
10,11,11,2140 Euclid Avenue.,NaN,Redwood City,CA,94061,US
11,12,12,1044 Middlefield Road,2nd Floor,Redwood City,CA,94063,US
12,13,13,399 Marine Parkway.,NaN,Redwood City,CA,94065,US
13,14,14,660 Veterans Blvd.,NaN,Redwood City,CA,94063,US
14,15,15,1500 Valencia Street,NaN,San Francisco,CA,94110,US
15,16,16,1161 South Bernardo,NaN,Sunnyvale,CA,94087,US
16,17,17,409 South Spruce Avenue,NaN,South San Francisco,CA,94080,US
17,18,18,114 Fifth Avenue,NaN,Redwood City,CA,94063,US
18,19,19,19 West 39th Avenue,NaN,San Mateo,CA,94403,US
19,20,21,123 El Camino Real,NaN,Belmont,CA,94002,US
20,21,22,2013 Avenue of the fellows,Suite 100,San Francisco,CA,94103,US

In [ ]:
data = pd.read_csv('https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv')

In [ ]:
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
list[data.columns]

list[Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')]

In [ ]:
data.head(100)[['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age','Ticket', 'Fare', 'Cabin']]

,PassengerId,Survived,Pclass,Name,Sex,Age,Ticket,Fare,Cabin
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,A/5 21171,7.2500,NaN
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,PC 17599,71.2833,C85
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,STON/O2. 3101282,7.9250,NaN
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,113803,53.1000,C123
4,5,0,3,"Allen, Mr. William Henry",male,35.0,373450,8.0500,NaN
...,...,...,...,...,...,...,...,...,...
95,96,0,3,"Shorney, Mr. Charles Joseph",male,NaN,374910,8.0500,NaN
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,PC 17754,34.6542,A5
97,98,1,1,"Greenfield, Mr. William Bertram",male,23.0,PC 17759,63.3583,D10 D12
98,99,1,2,"Doling, Mrs. John T (Ada Julia Bone)",female,34.0,231919,23.0000,NaN
99,100,0,2,"Kantor, Mr. Sinai",male,34.0,244367,26.0000,NaN

In [ ]:
data.dtypes#----- to find the type of data of each colum

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [ ]:
data.info()#-----all info regarding data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [ ]:
data.describe()#---- it will give small statictical analysis of data set which has only numric values

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [ ]:
data[['Name', 'Sex','Ticket']]#--- taking only object base data beacue in upper report we have only report for numric data, if you want to take the report for string(object ) base columns pleasefollow

,Name,Sex,Ticket
0,"Braund, Mr. Owen Harris",male,A/5 21171
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,PC 17599
2,"Heikkinen, Miss. Laina",female,STON/O2. 3101282
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,113803
4,"Allen, Mr. William Henry",male,373450
...,...,...,...
886,"Montvila, Rev. Juozas",male,211536
887,"Graham, Miss. Margaret Edith",female,112053
888,"Johnston, Miss. Catherine Helen ""Carrie""",female,W./C. 6607
889,"Behr, Mr. Karl Howell",male,111369
890,"Dooley, Mr. Patrick",male,370376

In [ ]:
data[['Name', 'Sex','Ticket']].describe()

                           Name   Sex  Ticket
count                       891   891     891
unique                      891     2     681
top     Braund, Mr. Owen Harris  male  347082
freq                          1   577       7

In [ ]:
#if there are 1000+ columns then we have need not to write colum names based on data type mannualy

In [ ]:
data.dtypes#--- data type of entire is series

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [ ]:
type(data.dtypes)

pandas.core.series.Series

In [ ]:
data.dtypes == 'object'

PassengerId    False
Survived       False
Pclass         False
Name            True
Sex             True
Age            False
SibSp          False
Parch          False
Ticket          True
Fare           False
Cabin           True
Embarked        True
dtype: bool

In [ ]:
data.dtypes[data.dtypes == 'object']

Name        object
Sex         object
Ticket      object
Cabin       object
Embarked    object
dtype: object

In [ ]:
data.dtypes[data.dtypes == 'object'].index

Index(['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked'], dtype='object')

In [ ]:
non_numric=data[data.dtypes[data.dtypes == 'object'].index]

In [ ]:
non_numric

,Name,Sex,Ticket,Cabin,Embarked
0,"Braund, Mr. Owen Harris",male,A/5 21171,NaN,S
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,PC 17599,C85,C
2,"Heikkinen, Miss. Laina",female,STON/O2. 3101282,NaN,S
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,113803,C123,S
4,"Allen, Mr. William Henry",male,373450,NaN,S
...,...,...,...,...,...
886,"Montvila, Rev. Juozas",male,211536,NaN,S
887,"Graham, Miss. Margaret Edith",female,112053,B42,S
888,"Johnston, Miss. Catherine Helen ""Carrie""",female,W./C. 6607,NaN,S
889,"Behr, Mr. Karl Howell",male,111369,C148,C
890,"Dooley, Mr. Patrick",male,370376,NaN,Q

In [ ]:
non_numric.describe()

                           Name   Sex  Ticket    Cabin Embarked
count                       891   891     891      204      889
unique                      891     2     681      147        3
top     Braund, Mr. Owen Harris  male  347082  B96 B98        S
freq                          1   577       7        4      644

In [ ]:
data.dtypes=='int64'

PassengerId     True
Survived        True
Pclass          True
Name           False
Sex            False
Age            False
SibSp           True
Parch           True
Ticket         False
Fare           False
Cabin          False
Embarked       False
dtype: bool

In [ ]:
data.dtypes[data.dtypes=='int64']

PassengerId    int64
Survived       int64
Pclass         int64
SibSp          int64
Parch          int64
dtype: object

In [ ]:
data.dtypes[data.dtypes=='int64'].index

Index(['PassengerId', 'Survived', 'Pclass', 'SibSp', 'Parch'], dtype='object')

In [ ]:
numric=data[data.dtypes[data.dtypes=='int64'].index]

In [ ]:
numric

     PassengerId  Survived  Pclass  SibSp  Parch
0              1         0       3      1      0
1              2         1       1      1      0
2              3         1       3      0      0
3              4         1       1      1      0
4              5         0       3      0      0
..           ...       ...     ...    ...    ...
886          887         0       2      0      0
887          888         1       1      0      0
888          889         0       3      1      2
889          890         1       1      0      0
890          891         0       3      0      0

[891 rows x 5 columns]

In [ ]:
data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
##find a data where survived is equal to 0

In [ ]:
data.dtypes['Survived']

dtype('int64')

In [ ]:
data['Survived']==0

0       True
1      False
2      False
3      False
4       True
       ...
886     True
887    False
888     True
889    False
890     True
Name: Survived, Length: 891, dtype: bool

In [ ]:
data[data['Survived']==0]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
##data which are servived and whcih are male

data[(data['Survived']==0) & (data['Sex']=='male')]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
881,882,0,3,"Markun, Mr. Johann",male,33.0,0,0,349257,7.8958,NaN,S
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
##Count os all of this

len(data[(data['Survived']==0) & (data['Sex']=='male')])

468

In [ ]:
len(data[(data['Survived']==0) & (data['Sex']=='female')])

81

In [ ]:
##number od male's on this ship

len(data[data['Sex']=='male'])

577

In [ ]:
##number od female's on this ship

len(data[data['Sex']=='female'])

314

In [ ]:
data[data['Fare'] == 512.329200]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
258,259,1,1,"Ward, Miss. Anna",female,35.0,0,0,PC 17755,512.3292,NaN,C
679,680,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,512.3292,B51 B53 B55,C
737,738,1,1,"Lesurer, Mr. Gustave J",male,35.0,0,0,PC 17755,512.3292,B101,C

In [ ]:
##Data for the people who has cabin facility

data[data['Cabin'].isnull()==False]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
...,...,...,...,...,...,...,...,...,...,...,...,...
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

In [ ]:
len(data[data['Cabin'].isnull()==False])

204

In [ ]:
##Add new column in data##

data['new_col'] = 'Pratik'

In [ ]:
data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new_col
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Pratik
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Pratik
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Pratik
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Pratik
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Pratik
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,Pratik
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,Pratik
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,Pratik
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,Pratik
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,Pratik

In [ ]:
##addition of tow columns

data['age_pclass'] = data['Age'] + data['Pclass']

In [ ]:
data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new_col,age_pclass
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,Pratik,25.0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Pratik,39.0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Pratik,29.0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Pratik,36.0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,Pratik,38.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,Pratik,29.0
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,Pratik,20.0
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,Pratik,NaN
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,Pratik,27.0
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,Pratik,35.0

In [ ]:
## Delete a column ##

data.drop('new_col',axis=1)##----thsi will be delete column not parmanantly

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,age_pclass
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,25.0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,39.0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,29.0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,36.0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,38.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,29.0
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,20.0
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,NaN
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,27.0
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,35.0

In [ ]:
data.drop('new_col',axis=1,inplace=True)## this will detele data parmanatly

In [ ]:
data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,age_pclass
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,25.0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,39.0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,29.0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,36.0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,38.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,29.0
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,20.0
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,NaN
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,27.0
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,35.0

In [ ]:
data.drop('age_pclass',axis=1,inplace=True)

In [ ]:
data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [ ]:
###### Now how to extraxt record based on a row ######

In [ ]:
#Extract row num 1#

data.iloc[0]#--- iloc will go thorugh internal indexing or default indexing

PassengerId                          1
Survived                             0
Pclass                               3
Name           Braund, Mr. Owen Harris
Sex                               male
Age                               22.0
SibSp                                1
Parch                                0
Ticket                       A/5 21171
Fare                              7.25
Cabin                              NaN
Embarked                             S
Name: 0, dtype: object

In [ ]:
data.loc[1]# loc will go after named indexing

PassengerId                                                    2
Survived                                                       1
Pclass                                                         1
Name           Cumings, Mrs. John Bradley (Florence Briggs Th...
Sex                                                       female
Age                                                         38.0
SibSp                                                          1
Parch                                                          0
Ticket                                                  PC 17599
Fare                                                     71.2833
Cabin                                                        C85
Embarked                                                       C
Name: 1, dtype: object

In [ ]:
data.loc[2:5]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q

In [ ]:
data.loc[101:106,['Survived','Pclass']]

     Survived  Pclass
101         0       3
102         0       1
103         0       3
104         0       3
105         0       3
106         1       3

In [ ]:
data[data['Age']>55]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
33,34,0,2,"Wheadon, Mr. Edward H",male,66.0,0,0,C.A. 24579,10.5000,NaN,S
54,55,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.0,0,1,113509,61.9792,B30,C
94,95,0,3,"Coxon, Mr. Daniel",male,59.0,0,0,364500,7.2500,NaN,S
96,97,0,1,"Goldschmidt, Mr. George B",male,71.0,0,0,PC 17754,34.6542,A5,C
116,117,0,3,"Connors, Mr. Patrick",male,70.5,0,0,370369,7.7500,NaN,Q
152,153,0,3,"Meo, Mr. Alfonzo",male,55.5,0,0,A.5. 11206,8.0500,NaN,S
170,171,0,1,"Van der hoef, Mr. Wyckoff",male,61.0,0,0,111240,33.5000,B19,S
174,175,0,1,"Smith, Mr. James Clinch",male,56.0,0,0,17764,30.6958,A7,C
195,196,1,1,"Lurette, Miss. Elise",female,58.0,0,0,PC 17569,146.5208,B80,C
232,233,0,2,"Sjostedt, Mr. Ernst Adolf",male,59.0,0,0,237442,13.5000,NaN,S
252,253,0,1,"Stead, Mr. William Thomas",male,62.0,0,0,113514,26.5500,C87,S
268,269,1,1,"Graham, Mrs. William Thompson (Edith Junkins)",female,58.0,0,1,PC 17582,153.4625,C125,S
275,276,1,1,"Andrews, Miss. Kornelia Theodosia",female,63.0,1,0,13502,77.9583,D7,S
280,281,0,3,"Duane, Mr. Frank",male,65.0,0,0,336439,7.7500,NaN,Q
326,327,0,3,"Nysveen, Mr. Johan Hansen",male,61.0,0,0,345364,6.2375,NaN,S
366,367,1,1,"Warren, Mrs. Frank Manley (Anna Sophia Atkinson)",female,60.0,1,0,110813,75.2500,D37,C
438,439,0,1,"Fortune, Mr. Mark",male,64.0,1,4,19950,263.0000,C23 C25 C27,S
456,457,0,1,"Millet, Mr. Francis Davis",male,65.0,0,0,13509,26.5500,E38,S
467,468,0,1,"Smart, Mr. John Montgomery",male,56.0,0,0,113792,26.5500,NaN,S
483,484,1,3,"Turkula, Mrs. (Hedwig)",female,63.0,0,0,4134,9.5875,NaN,S
487,488,0,1,"Kent, Mr. Edward Austin",male,58.0,0,0,11771,29.7000,B37,C
493,494,0,1,"Artagaveytia, Mr. Ramon",male,71.0,0,0,PC 17609,49.5042,NaN,C
545,546,0,1,"Nicholson, Mr. Arthur Ernest",male,64.0,0,0,693,26.0000,NaN,S
555,556,0,1,"Wright, Mr. George",male,62.0,0,0,113807,26.5500,NaN,S
570,571,1,2,"Harris, Mr. George",male,62.0,0,0,S.W./PP 752,10.5000,NaN,S
587,588,1,1,"Frolicher-Stehli, Mr. Maxmillian",male,60.0,1,1,13567,79.2000,B41,C
625,626,0,1,"Sutton, Mr. Frederick",male,61.0,0,0,36963,32.3208,D50,S
626,627,0,2,"Kirkland, Rev. Charles Leonard",male,57.0,0,0,219533,12.3500,NaN,Q
630,631,1,1,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,0,0,27042,30.0000,A23,S
647,648,1,1,"Simonius-Blumer, Col. Oberst Alfons",male,56.0,0,0,13213,35.5000,A26,C
659,660,0,1,"Newell, Mr. Arthur Webster",male,58.0,0,2,35273,113.2750,D48,C
672,673,0,2,"Mitchell, Mr. Henry Michael",male,70.0,0,0,C.A. 24580,10.5000,NaN,S
684,685,0,2,"Brown, Mr. Thomas William Solomon",male,60.0,1,1,29750,39.0000,NaN,S
694,695,0,1,"Weir, Col. John",male,60.0,0,0,113800,26.5500,NaN,S
745,746,0,1,"Crosby, Capt. Edward Gifford",male,70.0,1,1,WE/P 5735,71.0000,B22,S
772,773,0,2,"Mack, Mrs. (Mary)",female,57.0,0,0,S.O./P.P. 3,10.5000,E77,S
829,830,1,1,"Stone, Mrs. George Nelson (Martha Evelyn)",female,62.0,0,0,113572,80.0000,B28,NaN
851,852,0,3,"Svensson, Mr. Johan",male,74.0,0,0,347060,7.7750,NaN,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C

In [ ]:
data.dropna()#---- to drop the na(Null values) record row wise

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
...,...,...,...,...,...,...,...,...,...,...,...,...
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

In [ ]:
data.dropna(axis=1)#---- to drop the na(Null values) record column wise

,PassengerId,Survived,Pclass,Name,Sex,SibSp,Parch,Ticket,Fare
0,1,0,3,"Braund, Mr. Owen Harris",male,1,0,A/5 21171,7.2500
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,1,0,PC 17599,71.2833
2,3,1,3,"Heikkinen, Miss. Laina",female,0,0,STON/O2. 3101282,7.9250
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,1,0,113803,53.1000
4,5,0,3,"Allen, Mr. William Henry",male,0,0,373450,8.0500
...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,0,0,211536,13.0000
887,888,1,1,"Graham, Miss. Margaret Edith",female,0,0,112053,30.0000
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,1,2,W./C. 6607,23.4500
889,890,1,1,"Behr, Mr. Karl Howell",male,0,0,111369,30.0000
890,891,0,3,"Dooley, Mr. Patrick",male,0,0,370376,7.7500

In [ ]:
data.fillna('Pratik')#---- fill na values with some value

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,Pratik,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,Pratik,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,Pratik,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,Pratik,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,Pratik,1,2,W./C. 6607,23.4500,Pratik,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Pratik,Q

In [ ]:
###Group of records###

In [ ]:
data.groupby('Sex').count()

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
Sex,,,,,,,,,,,
female,314,314,314,314,261,314,314,314,314,97,312
male,577,577,577,577,453,577,577,577,577,107,577

In [ ]:
data.groupby('Sex').sum()['Fare']

Sex
female    13966.6628
male      14727.2865
Name: Fare, dtype: float64

In [ ]:
###devide a pclass by 3##

In [ ]:
data['new'] = data['Pclass']

In [ ]:
data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,3
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,1
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,3
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,1
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,2
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,1
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,3
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,1
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,3

In [ ]:
data['new'] = data['Pclass'].apply(lambda x : x/3)

In [ ]:
data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,1.000000
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0.333333
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1.000000
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,0.333333
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,0.666667
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,0.333333
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,1.000000
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,0.333333
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,1.000000

In [ ]:
###External function for div operation##

In [ ]:
def func1(x):
  return x/3

In [ ]:
data['new'] = data['Pclass'].apply(func1)

In [ ]:
data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,1.000000
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0.333333
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1.000000
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,0.333333
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,1.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,0.666667
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,0.333333
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,1.000000
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,0.333333
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,1.000000

In [ ]:
def func2(x):
  return len(x)

In [ ]:
data['new_len'] = data['Name'].apply(func2)

In [ ]:
data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new,new_len
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,1.000000,23
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0.333333,51
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1.000000,22
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,0.333333,44
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,1.000000,24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,0.666667,21
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,0.333333,28
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,1.000000,40
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,0.333333,21
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,1.000000,19

In [ ]:
### Write a function to create a new colum where put passanger id as it is if ID is lesser then 3 and when ID is grater then 3 put log of that value

In [ ]:
import math
def con1(x):
  if x<3:
    return x
  else:
    return math.log10(x)

In [ ]:
data['Log_value'] = data['PassengerId'].apply(con1)

In [ ]:
data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new,new_len,Log_value
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,1.000000,23,1.000000
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0.333333,51,2.000000
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1.000000,22,0.477121
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,0.333333,44,0.602060
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,1.000000,24,0.698970
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,0.666667,21,2.947924
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,0.333333,28,2.948413
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,1.000000,40,2.948902
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,0.333333,21,2.949390
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,1.000000,19,2.949878

In [ ]:
def conversion(x):
  if x == 'female':
    return 0
  else:
    return 1

In [ ]:
data['Sex_value'] = data['Sex'].apply(conversion)

In [ ]:
data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new,new_len,Log_value,Sex_value
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,1.000000,23,1.000000,1
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0.333333,51,2.000000,0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1.000000,22,0.477121,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,0.333333,44,0.602060,0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,1.000000,24,0.698970,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,0.666667,21,2.947924,1
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,0.333333,28,2.948413,0
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,1.000000,40,2.948902,0
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,0.333333,21,2.949390,1
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,1.000000,19,2.949878,1

In [ ]:
### Create a catogary as per face cost##
###0-100 = 'A'
###101-199 = 'B'
###200+ = 'C'

In [ ]:
def catogary(x):
  if x<=100:
    return 'A'
  elif x>100 and x<200:
    return 'B'
  else:
    return 'C'

In [ ]:
A=data['Catogary']  = data['Fare'].apply(catogary)

In [ ]:
data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new,new_len,Log_value,Sex_value,Catogary
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,1.000000,23,1.000000,1,A
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0.333333,51,2.000000,0,A
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1.000000,22,0.477121,0,A
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,0.333333,44,0.602060,0,A
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,1.000000,24,0.698970,1,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,0.666667,21,2.947924,1,A
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,0.333333,28,2.948413,0,A
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,1.000000,40,2.948902,0,A
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,0.333333,21,2.949390,1,A
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,1.000000,19,2.949878,1,A

In [ ]:
data.groupby(A).count()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,new,new_len,Log_value,Sex_value,Catogary
Fare,,,,,,,,,,,,,,,,,
A,838,838,838,838,838,666,838,838,838,838,161,836,838,838,838,838,838
B,33,33,33,33,33,30,33,33,33,33,26,33,33,33,33,33,33
C,20,20,20,20,20,18,20,20,20,20,17,20,20,20,20,20,20

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/google/colab/data_table.py", line 192, in _repr_mimebundle_
    dataframe = self._preprocess_dataframe()
  File "/usr/local/lib/python3.10/dist-packages/google/colab/data_table.py", line 180, in _preprocess_dataframe
    dataframe = dataframe.reset_index()
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/frame.py", line 6220, in reset_index
    new_obj.insert(
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/frame.py", line 4931, in insert
    raise ValueError(f"cannot insert {column}, already exists")
ValueError: cannot insert Fare, already exists
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/google/colab/data_table.py", line 204, in _repr_javascript_module_
    return self._gen_js(self._preprocess_dataframe())
  File "/usr/local/lib/python3.10/dist-packages/google/colab/data_table.py", line 180, in _preprocess_dataframe
    dataframe = dataframe.reset_index()
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/frame.py", line 6220, in reset_index
    new_obj.insert(
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/frame.py", line 4931, in insert
    raise ValueError(f"cannot insert {column}, already exists")
ValueError: cannot insert Fare, already exists

In [ ]:
#####################################################################   NEW  DATA   #################################################################################

In [ ]:
## Convert dict into data frame

In [ ]:
d1 = {'k1':[1,2,3,4,5],
      'k2':[6,7,8,9,10],
      'k3':[11,12,13,14,15],}

In [ ]:
import pandas as pd

In [ ]:
pd.DataFrame(d1)

   k1  k2  k3
0   1   6  11
1   2   7  12
2   3   8  13
3   4   9  14
4   5  10  15

In [ ]:
d2 = {'k1':[1,2,3,4],
      'k2':[6,7,8,9,10],
      'k3':[11,12,13,14,15],}

In [ ]:
pd.DataFrame(d2)

ValueError: All arrays must be of the same length

In [ ]:
## Keep one imp point while converting dict into dataframe is that the number of values must be equal ##

In [ ]:
# To change index name #
d3 = {'k1':[1,2,3,4,5],
      'k2':[6,7,8,9,10],
      'k3':[11,12,13,14,15],}

In [ ]:
df1=pd.DataFrame(d3 )

In [ ]:
df1

   k1  k2  k3
0   1   6  11
1   2   7  12
2   3   8  13
3   4   9  14
4   5  10  15

In [ ]:
d4 = {'k1':[1,2,3,4,5,'pratik'],
      'k2':[6,7,8,'kumar',9,10],
      'k3':[11,12,13,14,15,'dombale']}

In [ ]:
df2=pd.DataFrame(d4)

In [ ]:
df2

       k1     k2       k3
0       1      6       11
1       2      7       12
2       3      8       13
3       4  kumar       14
4       5      9       15
5  pratik     10  dombale

In [ ]:
## Marge operation ##

In [ ]:
pd.merge(df1,df2)## Only sow  common parts

  k1 k2  k3
0  1  6  11
1  2  7  12
2  3  8  13

In [ ]:
pd.merge(df1,df2,how= 'inner',on='k1')### meaning of 'on'----it will match withrespect to k1

  k1  k2_x  k3_x   k2_y k3_y
0  1     6    11      6   11
1  2     7    12      7   12
2  3     8    13      8   13
3  4     9    14  kumar   14
4  5    10    15      9   15

In [ ]:
pd.merge(df1,df2,how= 'inner',on='k3')

   k1_x  k2_x  k3 k1_y   k2_y
0     1     6  11    1      6
1     2     7  12    2      7
2     3     8  13    3      8
3     4     9  14    4  kumar
4     5    10  15    5      9

In [ ]:
pd.merge(df1,df2,how= 'left',on='k3')#--- bring all data from left hand side i.e df1

   k1_x  k2_x  k3 k1_y   k2_y
0     1     6  11    1      6
1     2     7  12    2      7
2     3     8  13    3      8
3     4     9  14    4  kumar
4     5    10  15    5      9

In [ ]:
pd.merge(df1,df2,how= 'outer',on='k3')#----- bring every combination from left and right

   k1_x  k2_x       k3    k1_y   k2_y
0   1.0   6.0       11       1      6
1   2.0   7.0       12       2      7
2   3.0   8.0       13       3      8
3   4.0   9.0       14       4  kumar
4   5.0  10.0       15       5      9
5   NaN   NaN  dombale  pratik     10

In [ ]:
d11 = {'a':[1,2,3,4,5],
      'b':[6,7,8,9,10],
      'c':[11,12,13,14,15],}

In [ ]:
d12 = {'k1':[1,2,3,4,5,'pratik'],
      'k2':[6,7,8,'kumar',9,10],
      'k3':[11,12,13,14,15,'dombale']}

In [ ]:
df11 = pd.DataFrame(d11)

In [ ]:
df11

   a   b   c
0  1   6  11
1  2   7  12
2  3   8  13
3  4   9  14
4  5  10  15

In [ ]:
df12 = pd.DataFrame(d12)

In [ ]:
df12

       k1     k2       k3
0       1      6       11
1       2      7       12
2       3      8       13
3       4  kumar       14
4       5      9       15
5  pratik     10  dombale

In [ ]:
## Now how to marge to data sets which are having different coloumn names----- Use left on and right on operations

In [ ]:
pd.merge(df11,df12,how = 'left',left_on = 'a',right_on = 'k1')

   a   b   c k1     k2  k3
0  1   6  11  1      6  11
1  2   7  12  2      7  12
2  3   8  13  3      8  13
3  4   9  14  4  kumar  14
4  5  10  15  5      9  15

In [ ]:
## Difference between merge and join is that join matches the indexes and merge chcek for the column values

In [ ]:
pd.concat([df11,df12],axis=0)#----- Row wise concatinating

     a     b     c      k1     k2       k3
0  1.0   6.0  11.0     NaN    NaN      NaN
1  2.0   7.0  12.0     NaN    NaN      NaN
2  3.0   8.0  13.0     NaN    NaN      NaN
3  4.0   9.0  14.0     NaN    NaN      NaN
4  5.0  10.0  15.0     NaN    NaN      NaN
0  NaN   NaN   NaN       1      6       11
1  NaN   NaN   NaN       2      7       12
2  NaN   NaN   NaN       3      8       13
3  NaN   NaN   NaN       4  kumar       14
4  NaN   NaN   NaN       5      9       15
5  NaN   NaN   NaN  pratik     10  dombale

In [ ]:
pd.concat([df11,df12],axis=1)#----- Column wise concatinating

     a     b     c      k1     k2       k3
0  1.0   6.0  11.0       1      6       11
1  2.0   7.0  12.0       2      7       12
2  3.0   8.0  13.0       3      8       13
3  4.0   9.0  14.0       4  kumar       14
4  5.0  10.0  15.0       5      9       15
5  NaN   NaN   NaN  pratik     10  dombale